import { Award, Check, Code2, Copy, ExternalLink, GraduationCap, Layers3, Mail, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { motion } from 'framer-motion'
import { isConfigured, portfolio, type Project } from '../../data/portfolio'
import { Reveal } from '../common/Reveal'
import { SectionHeading } from '../common/SectionHeading'
import { ProjectCaseStudy } from '../projects/ProjectCaseStudy'

export function RecruiterSnapshot() { return <section id="snapshot" className="snapshot wrap" aria-label="Recruiter snapshot">{portfolio.snapshot.map((item, index) => <Reveal key={item} className="snapshot-item"><strong>0{index + 1}</strong><span>{item}</span></Reveal>)}</section> }

export function About() { return <section id="about" className="section wrap"><SectionHeading eyebrow="About" title="Engineering across the whole product." description="Enterprise foundations, frontend craft, and applied AI—connected by practical problem solving."/><div className="about-grid"><Reveal><p className="about-copy">{portfolio.personal.about}</p></Reveal><Reveal className="build-flow"><h3>How I build</h3><div>{portfolio.buildSteps.map((step, index) => <span key={step}>{step}{index < portfolio.buildSteps.length - 1 && <i>→</i>}</span>)}</div></Reveal></div></section> }

export function Experience() { return <section id="experience" className="section wrap"><SectionHeading eyebrow="Experience" title="Professional work, end to end." description="Grounded contributions across enterprise products and project-based client work."/><div className="timeline">{portfolio.experiences.map((item) => <Reveal className="experience-card" key={item.role}><span className="timeline-dot"/><div className="card-top"><div><p className="period">{item.period}</p><h3>{item.role}</h3><p className="company">{item.company}</p></div></div><p>{item.summary}</p><ul>{item.highlights.map((point) => <li key={point}>{point}</li>)}</ul><div className="tags">{item.stack.map((tag) => <span key={tag}>{tag}</span>)}</div></Reveal>)}</div></section> }

export function Skills() { const [active, setActive] = useState('All'); const levels = ['All', 'Core', 'Working knowledge', 'Project exposure'] as const; const groups = portfolio.skills.filter((group) => active === 'All' || group.level === active); return <section id="skills" className="section wrap"><SectionHeading eyebrow="Capabilities" title="Tools chosen for the problem." description="Core professional skills are distinguished from working knowledge and project exposure—without arbitrary percentages."/><div className="filters" role="group" aria-label="Filter skill groups">{levels.map((level) => <button key={level} className={active === level ? 'active' : ''} onClick={() => setActive(level)} aria-pressed={active === level}>{level}</button>)}</div><motion.div layout className="skills-grid">{groups.map((group) => <motion.article layout className="skill-card" key={group.name}><div><Layers3 size={20}/><span>{group.level}</span></div><h3>{group.name}</h3><ul>{group.skills.map((skill) => <li key={skill}>{skill}</li>)}</ul></motion.article>)}</motion.div></section> }

export function Projects() { const [selected, setSelected] = useState<Project | null>(null); return <section id="projects" className="section wrap"><SectionHeading eyebrow="Selected work" title="Products, prototypes, and practical systems." description="A mix of enterprise full-stack engineering and focused AI exploration."/><div className="projects-grid">{portfolio.projects.map((project) => <Reveal className={`project-card ${project.featured ? 'featured' : ''}`} key={project.title}><div className="project-meta"><span>{project.status}</span>{project.featured && <Sparkles size={17}/>}</div><h3>{project.title}</h3><p>{project.description}</p><p className="built"><strong>Built:</strong> {project.built}</p><div className="tags">{project.stack.map((tag) => <span key={tag}>{tag}</span>)}</div><p className="outcome"><strong>Outcome / learning:</strong> {project.outcome}</p><div className="project-actions">{project.caseStudy && <button onClick={() => setSelected(project)}>Read case study</button>}{project.github && <a href={project.github} target="_blank" rel="noreferrer"><Code2 size={16}/> Code</a>}{project.live && <a href={project.live} target="_blank" rel="noreferrer"><ExternalLink size={16}/> Live</a>}</div></Reveal>)}</div>{selected && <ProjectCaseStudy project={selected} close={() => setSelected(null)}/>}</section> }

export function Education() { return <section id="education" className="section wrap"><SectionHeading eyebrow="Learning" title="Education, credentials, and progression."/><div className="education-grid"><div>{portfolio.education.map((item) => <Reveal className="education-card" key={item.degree}><GraduationCap/><div><p className="period">{item.period}</p><h3>{item.degree}</h3><p>{item.school}</p>{item.detail && <span>{item.detail}</span>}</div></Reveal>)}</div><div>{portfolio.certifications.map((item) => <Reveal className="cert-card" key={item.title}><Award/><div><h3>{item.title}</h3><p>{item.detail}</p>{item.credentialUrl && <a href={item.credentialUrl}>View credential</a>}</div></Reveal>)}</div></div><div className="journey"><h3>Engineering journey</h3>{portfolio.journey.map((step) => <span key={step}>{step}</span>)}</div></section> }

export function Contact() { const [copied, setCopied] = useState(false); const emailReady = isConfigured(portfolio.contact.email); const linkedinReady = isConfigured(portfolio.contact.linkedinUrl); const copy = async () => { if (!emailReady) return; await navigator.clipboard.writeText(portfolio.contact.email); setCopied(true); window.setTimeout(() => setCopied(false), 1800) }; return <section id="contact" className="section wrap"><Reveal className="contact-panel"><span className="eyebrow">Contact</span><h2>Let’s build something useful.</h2><p>Have a full-stack, .NET, AI, SDK, or software engineering opportunity? Let’s connect.</p><div className="contact-actions">{emailReady && <><a className="button primary" href={`mailto:${portfolio.contact.email}`}><Mail size={18}/> Email me</a><button className="button secondary" onClick={copy}>{copied ? <Check size={18}/> : <Copy size={18}/>} {copied ? 'Copied' : 'Copy email'}</button></>} {linkedinReady && <a className="button secondary" href={portfolio.contact.linkedinUrl} target="_blank" rel="noreferrer">LinkedIn</a>}<a className="button secondary" href={portfolio.contact.githubUrl} target="_blank" rel="noreferrer"><Code2 size={18}/> GitHub</a>{portfolio.contact.resumeEnabled && <a className="button secondary" href={portfolio.contact.resumePath} download>Download resume</a>}</div>{!emailReady && !linkedinReady && <p className="config-note">Email and LinkedIn details are being configured. GitHub is available now.</p>}</Reveal></section> }
